INITIAL_QUESTIONS = [
    {"id": "q1", "text": "Is the GA4 property created and tracking ID obtained?", "category": "Basic Setup", "severity": "Critical",
     "why": "Without a GA4 property, no data can be collected at all.", "fix": "Create a GA4 property in Google Analytics and note the Measurement ID."},
    {"id": "q2", "text": "Is the GA4 tag installed on all pages of the website?", "category": "Basic Setup", "severity": "Critical",
     "why": "Missing tags on some pages create gaps in your data.", "fix": "Verify the GA4 tag fires on every page using GA4 DebugView or Tag Assistant."},
    {"id": "q3", "text": "Is Google Tag Manager being used for implementation?", "category": "Basic Setup", "severity": "Critical",
     "why": "GTM makes future tracking changes easier without code deployments.", "fix": "Migrate hardcoded GA4 tags into Google Tag Manager."},
    {"id": "q4", "text": "Is the data stream configured correctly?", "category": "Basic Setup", "severity": "Critical",
     "why": "An incorrectly configured data stream can send data to the wrong property or miss key settings.", "fix": "Check the data stream settings in GA4 Admin > Data Streams."},
    {"id": "q5", "text": "Are key conversion events marked as conversions in GA4?", "category": "Event Tracking", "severity": "Critical",
     "why": "Unmarked conversions won't show up in conversion reports or feed into Google Ads.", "fix": "Go to GA4 Admin > Events and toggle 'Mark as conversion' for key events."},
    {"id": "q6", "text": "Is purchase/transaction tracking implemented (for ecommerce)?", "category": "Event Tracking", "severity": "Critical",
     "why": "Without this, revenue and transaction data is invisible.", "fix": "Implement GA4's Enhanced Ecommerce purchase event with required parameters."},
    {"id": "q7", "text": "Are form submission events tracked?", "category": "Event Tracking", "severity": "Critical",
     "why": "Form submissions are often key lead-gen conversions.", "fix": "Add a form_submit event trigger in GTM."},
    {"id": "q8", "text": "Is scroll depth tracking enabled?", "category": "Event Tracking", "severity": "Critical",
     "why": "Scroll tracking helps measure content engagement.", "fix": "Enable GA4's built-in scroll tracking in the Enhanced Measurement settings."},
    {"id": "q9", "text": "Are outbound link clicks tracked?", "category": "Event Tracking", "severity": "Critical",
     "why": "Outbound clicks show referral and partner traffic behavior.", "fix": "Enable Outbound Click tracking under Enhanced Measurement."},
    {"id": "q10", "text": "Are internal traffic filters set up (to exclude team's own visits)?", "category": "Configuration & Quality", "severity": "Warning",
     "why": "Internal visits inflate and skew your real user metrics.", "fix": "Define internal traffic rules in GA4 Admin > Data Settings > Data Filters."},
    {"id": "q11", "text": "Is cross-domain tracking configured (if the site spans multiple domains)?", "category": "Configuration & Quality", "severity": "Warning",
     "why": "Without this, sessions break when users move between your domains.", "fix": "Add all relevant domains under Data Stream > Configure tag settings > Configure your domains."},
    {"id": "q12", "text": "Are custom dimensions/metrics defined for business-specific data?", "category": "Configuration & Quality", "severity": "Warning",
     "why": "Without custom dimensions, business-specific data can't be analyzed.", "fix": "Define custom dimensions in GA4 Admin > Custom Definitions."},
    {"id": "q13", "text": "Is the Google Ads account linked to GA4?", "category": "Configuration & Quality", "severity": "Warning",
     "why": "Without this link, conversion data can't be used for ad optimization.", "fix": "Link Google Ads in GA4 Admin > Product Links."},
    {"id": "q14", "text": "Is Search Console linked to GA4?", "category": "Configuration & Quality", "severity": "Warning",
     "why": "This link enables organic search query reporting inside GA4.", "fix": "Link Search Console in GA4 Admin > Product Links."},
    {"id": "q15", "text": "Is a consent banner implemented on the website?", "category": "Privacy & Consent", "severity": "Critical",
     "why": "Required for legal compliance in many regions (GDPR, DPDP Act etc).", "fix": "Implement a consent management platform (CMP) banner."},
    {"id": "q16", "text": "Is GA4 Consent Mode v2 configured?", "category": "Privacy & Consent", "severity": "Critical",
     "why": "Without Consent Mode v2, data collection may violate consent regulations.", "fix": "Implement Consent Mode v2 tags in GTM tied to your CMP."},
    {"id": "q17", "text": "Is data retention set to the appropriate period?", "category": "Privacy & Consent", "severity": "Critical",
     "why": "Incorrect retention settings can violate privacy policy or lose historical data early.", "fix": "Set retention period in GA4 Admin > Data Settings > Data Retention."},
    {"id": "q18", "text": "Are any PII fields being accidentally sent to GA4?", "category": "Privacy & Consent", "severity": "Critical",
     "why": "Sending PII to GA4 violates Google's terms of service and privacy law.", "fix": "Audit event parameters and URLs for emails, names, or phone numbers being passed."},
]
